# Generated by Django 4.2.11 on 2024-04-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('screening_test', models.CharField(max_length=255)),
                ('interval_years', models.PositiveIntegerField()),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening_app.screeningguideline')),
            ],
        ),
    ]
