# Generated by Django 4.2.11 on 2024-04-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0005_patient_screeningguideline_questions_patientanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningguideline',
            name='rules',
            field=models.JSONField(default=dict),
        ),
    ]
